{
  "openapi": "3.0.0",
  "info": {
    "title": "Rese",
    "description": "Rese API",
    "version": "0.0.1"
  },
  "servers": [
    {
      "url": "http://localhost:8000",
      "description": "Local server (php artisan serve)"
    },
    {
      "url": "http://rese-backend.test",
      "description": "Local server (Herd)"
    }
  ],
  "paths": {
    "/areas": {
      "get": {
        "tags": ["Area"],
        "summary": "エリア一覧取得",
        "description": "エリア一覧を取得する",
        "operationId": "get-areas",
        "responses": {
          "200": {
            "$ref": "#/components/responses/get-areas-200"
          }
        }
      }
    },
    "/auth/status": {
      "get": {
        "tags": ["Auth"],
        "summary": "認証状態取得",
        "description": "認証状態を取得する",
        "operationId": "get-auth-status",
        "responses": {
          "200": {
            "$ref": "#/components/responses/get-auth-status-200"
          }
        }
      }
    },
    "/customers/{user}": {
      "get": {
        "tags": ["Customer"],
        "summary": "会員情報取得",
        "description": "ユーザー(一般会員)の情報を取得する",
        "operationId": "get-customer",
        "parameters": [
          {
            "$ref": "#/components/parameters/user-id"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/show-customer-200"
          },
          "401": {
            "$ref": "#/components/responses/unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/forbidden"
          },
          "404": {
            "$ref": "#/components/responses/not-found"
          }
        }
      }
    },
    "/customers/{user}/shops/{shop}/favorite": {
      "post": {
        "tags": ["Favorite"],
        "summary": "お気に入り登録",
        "description": "ユーザー(一般会員)が飲食店をお気に入り登録する",
        "operationId": "post-customer-shop-favorite",
        "parameters": [
          {
            "$ref": "#/components/parameters/user-id"
          },
          {
            "$ref": "#/components/parameters/shop-id"
          }
        ],
        "responses": {
          "201": {
            "$ref": "#/components/responses/created"
          },
          "401": {
            "$ref": "#/components/responses/unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/forbidden"
          },
          "404": {
            "$ref": "#/components/responses/not-found"
          },
          "422": {
            "$ref": "#/components/responses/unprocessable-entity"
          }
        }
      },
      "delete": {
        "tags": ["Favorite"],
        "summary": "お気に入り解除",
        "description": "ユーザー(一般会員)が飲食店のお気に入りを解除する",
        "operationId": "delete-customer-shop-favorite",
        "parameters": [
          {
            "$ref": "#/components/parameters/user-id"
          },
          {
            "$ref": "#/components/parameters/shop-id"
          }
        ],
        "responses": {
          "204": {
            "$ref": "#/components/responses/no-content"
          },
          "401": {
            "$ref": "#/components/responses/unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/forbidden"
          },
          "404": {
            "$ref": "#/components/responses/not-found"
          },
          "422": {
            "$ref": "#/components/responses/unprocessable-entity"
          }
        }
      }
    },
    "/genres": {
      "get": {
        "tags": ["Genre"],
        "summary": "ジャンル一覧取得",
        "description": "ジャンル一覧を取得する",
        "operationId": "get-genres",
        "responses": {
          "200": {
            "$ref": "#/components/responses/get-genres-200"
          }
        }
      }
    },
    "/shops": {
      "get": {
        "tags": ["Shop"],
        "summary": "飲食店一覧取得",
        "description": "飲食店一覧を取得する",
        "operationId": "get-shops",
        "parameters": [
          {
            "$ref": "#/components/parameters/area-query"
          },
          {
            "$ref": "#/components/parameters/genre-query"
          },
          {
            "$ref": "#/components/parameters/search-query"
          },
          {
            "$ref": "#/components/parameters/page-query"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/get-shops-200"
          }
        }
      }
    },
    "/sanctum/csrf-cookie": {
      "get": {
        "tags": ["Auth"],
        "summary": "CSRFトークン取得",
        "description": "CSRFトークンを取得する",
        "operationId": "get-sanctum-csrf-cookie",
        "responses": {
          "204": {
            "$ref": "#/components/responses/get-sanctum-csrf-cookie-204"
          }
        }
      }
    },
    "/auth/register": {
      "post": {
        "tags": ["Auth"],
        "summary": "会員登録",
        "description": "ユーザー(一般会員)を新規登録する",
        "operationId": "post-auth-register",
        "requestBody": {
          "$ref": "#/components/requestBodies/post-auth-register"
        },
        "responses": {
          "201": {
            "$ref": "#/components/responses/created"
          },
          "204": {
            "$ref": "#/components/responses/no-content"
          },
          "422": {
            "$ref": "#/components/responses/post-auth-register-422"
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "ログイン",
        "description": "ユーザー(一般会員)のログイン処理を行う",
        "operationId": "post-auth-login",
        "requestBody": {
          "$ref": "#/components/requestBodies/post-auth-login"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/ok"
          },
          "204": {
            "$ref": "#/components/responses/no-content"
          },
          "422": {
            "$ref": "#/components/responses/post-auth-login-422"
          }
        }
      }
    },
    "/auth/logout": {
      "post": {
        "tags": ["Auth"],
        "summary": "ログアウト",
        "description": "ユーザー(一般会員)のログアウト処理を行う",
        "operationId": "post-auth-logout",
        "responses": {
          "204": {
            "$ref": "#/components/responses/no-content"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "pagination": {
        "description": "ページネーション",
        "required": ["meta", "links"],
        "properties": {
          "meta": {
            "description": "ページネーションメタ情報",
            "required": [
              "current_page",
              "from",
              "last_page",
              "links",
              "path",
              "per_page",
              "to",
              "total"
            ],
            "properties": {
              "current_page": {
                "description": "現在のページ番号",
                "type": "integer",
                "minimum": 1
              },
              "from": {
                "description": "現在のページの最初のレコード番号",
                "oneOf": [
                  {
                    "type": "null"
                  },
                  {
                    "type": "integer",
                    "minimum": 1
                  }
                ]
              },
              "last_page": {
                "description": "最終ページ番号",
                "type": "integer",
                "minimum": 1
              },
              "links": {
                "description": "ページネーションリンク",
                "type": "array",
                "items": {
                  "required": ["url", "label", "active"],
                  "properties": {
                    "url": {
                      "description": "リンクURL",
                      "oneOf": [
                        {
                          "type": "null"
                        },
                        {
                          "type": "string",
                          "format": "uri"
                        }
                      ]
                    },
                    "label": {
                      "description": "リンクラベル",
                      "type": "string"
                    },
                    "active": {
                      "description": "アクティブかどうか",
                      "type": "boolean"
                    }
                  },
                  "type": "object"
                }
              },
              "path": {
                "description": "現在のページのURL",
                "type": "string",
                "format": "uri"
              },
              "per_page": {
                "description": "1ページあたりの件数",
                "type": "integer",
                "minimum": 1
              },
              "to": {
                "description": "現在のページの最後のレコード番号",
                "oneOf": [
                  {
                    "type": "null"
                  },
                  {
                    "type": "integer",
                    "minimum": 1
                  }
                ]
              },
              "total": {
                "description": "総件数",
                "type": "integer",
                "minimum": 0
              }
            },
            "type": "object"
          },
          "links": {
            "description": "ページネーションリンク",
            "required": ["first", "last", "prev", "next"],
            "properties": {
              "first": {
                "description": "最初のページのURL",
                "type": "string",
                "format": "uri"
              },
              "last": {
                "description": "最後のページのURL",
                "type": "string",
                "format": "uri"
              },
              "prev": {
                "description": "前のページのURL",
                "oneOf": [
                  {
                    "type": "null"
                  },
                  {
                    "type": "string",
                    "format": "uri"
                  }
                ]
              },
              "next": {
                "description": "次のページのURL",
                "oneOf": [
                  {
                    "type": "null"
                  },
                  {
                    "type": "string",
                    "format": "uri"
                  }
                ]
              }
            },
            "type": "object"
          }
        },
        "type": "object"
      }
    },
    "responses": {
      "show-customer-200": {
        "description": "OK",
        "content": {
          "application/json": {
            "schema": {
              "required": ["name"],
              "properties": {
                "name": {
                  "type": "string",
                  "example": "テストユーザー"
                }
              },
              "type": "object"
            }
          }
        }
      },
      "ok": {
        "description": "リクエストが成功しリソースが見つかった"
      },
      "created": {
        "description": "リクエストが成功しリソースが作成された"
      },
      "no-content": {
        "description": "リクエストが成功しリソースが存在しない"
      },
      "found": {
        "description": "リクエストが成功しリソースが見つかった"
      },
      "unauthorized": {
        "description": "認証エラー"
      },
      "forbidden": {
        "description": "認可エラー"
      },
      "not-found": {
        "description": "指定されたリソースが存在しない"
      },
      "conflict": {
        "description": "リクエストが競合している"
      },
      "unprocessable-entity": {
        "description": "リクエストが正しくない"
      },
      "get-sanctum-csrf-cookie-204": {
        "description": "CSRFトークン取得成功",
        "headers": {
          "Set-Cookie": {
            "description": "CSRFトークンをCookieにセット",
            "required": true,
            "schema": {
              "type": "string",
              "example": "XSRF-TOKEN=eyJpdiI6Ij"
            }
          }
        }
      },
      "post-auth-register-422": {
        "description": "バリデーションエラーまたはメールアドレスが登録済み",
        "content": {
          "application/json": {
            "schema": {
              "required": ["message", "errors"],
              "properties": {
                "message": {
                  "type": "string"
                },
                "errors": {
                  "properties": {
                    "name": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "email": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "password": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            },
            "examples": {
              "post-auth-register-422-required": {
                "summary": "名前、メールアドレス、パスワードが入力されていない場合",
                "value": {
                  "message": "名前を入力してください (and 2 more errors)",
                  "errors": {
                    "name": ["名前を入力してください"],
                    "email": ["メールアドレスを入力してください"],
                    "password": ["パスワードを入力してください"]
                  }
                }
              },
              "post-auth-register-422-email": {
                "summary": "メールアドレスが正しい形式でない場合",
                "value": {
                  "message": "メールアドレスを正しい形式で入力してください",
                  "errors": {
                    "email": ["メールアドレスを正しい形式で入力してください"]
                  }
                }
              },
              "post-auth-register-422-password": {
                "summary": "パスワードが8文字未満の場合",
                "value": {
                  "message": "パスワードは8文字以上で入力してください",
                  "errors": {
                    "password": ["パスワードは8文字以上で入力してください"]
                  }
                }
              }
            }
          }
        }
      },
      "post-auth-login-422": {
        "description": "バリデーションエラーまたは未登録",
        "content": {
          "application/json": {
            "schema": {
              "required": ["message", "errors"],
              "properties": {
                "message": {
                  "type": "string"
                },
                "errors": {
                  "properties": {
                    "email": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "password": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                  },
                  "type": "object"
                }
              },
              "type": "object"
            },
            "examples": {
              "post-auth-login-422-required": {
                "summary": "メールアドレス、パスワードが入力されていない場合",
                "value": {
                  "message": "メールアドレスを入力してください (and 1 more error)",
                  "errors": {
                    "email": ["メールアドレスを入力してください"],
                    "password": ["パスワードを入力してください"]
                  }
                }
              },
              "post-auth-login-422-email": {
                "summary": "ユーザーが登録されていない場合",
                "value": {
                  "message": "認証情報が登録されていません",
                  "errors": {
                    "email": ["認証情報が登録されていません"]
                  }
                }
              }
            }
          }
        }
      },
      "get-auth-status-200": {
        "description": "認証状態取得成功",
        "content": {
          "application/json": {
            "schema": {
              "required": ["status"],
              "properties": {
                "status": {
                  "type": "string",
                  "enum": ["guest", "customer"]
                },
                "id": {
                  "type": "integer",
                  "format": "int64"
                }
              },
              "type": "object"
            },
            "examples": {
              "get-auth-status-200-guest": {
                "summary": "未認証の状態",
                "value": {
                  "status": "guest"
                }
              },
              "get-auth-status-200-customer": {
                "summary": "一般会員として認証済みの状態",
                "value": {
                  "status": "customer",
                  "id": 1
                }
              }
            }
          }
        }
      },
      "get-areas-200": {
        "description": "エリア一覧取得成功",
        "content": {
          "application/json": {
            "schema": {
              "required": ["areas"],
              "properties": {
                "areas": {
                  "type": "array",
                  "items": {
                    "required": ["id", "name"],
                    "properties": {
                      "id": {
                        "type": "integer",
                        "format": "int64"
                      },
                      "name": {
                        "type": "string"
                      }
                    },
                    "type": "object"
                  }
                }
              },
              "type": "object"
            },
            "examples": {
              "get-areas-200-example": {
                "summary": "エリア一覧の例",
                "value": {
                  "areas": [
                    {
                      "id": 1,
                      "name": "東京"
                    },
                    {
                      "id": 2,
                      "name": "大阪"
                    },
                    {
                      "id": 3,
                      "name": "福岡"
                    }
                  ]
                }
              }
            }
          }
        }
      },
      "get-genres-200": {
        "description": "ジャンル一覧取得成功",
        "content": {
          "application/json": {
            "schema": {
              "required": ["genres"],
              "properties": {
                "genres": {
                  "type": "array",
                  "items": {
                    "required": ["id", "name"],
                    "properties": {
                      "id": {
                        "type": "integer",
                        "format": "int64"
                      },
                      "name": {
                        "type": "string"
                      }
                    },
                    "type": "object"
                  }
                }
              },
              "type": "object"
            },
            "examples": {
              "get-genres-200-example": {
                "summary": "ジャンル一覧の例",
                "value": {
                  "genres": [
                    {
                      "id": 1,
                      "name": "和食"
                    },
                    {
                      "id": 2,
                      "name": "中華"
                    },
                    {
                      "id": 3,
                      "name": "イタリアン"
                    }
                  ]
                }
              }
            }
          }
        }
      },
      "get-shops-200": {
        "description": "飲食店一覧取得成功",
        "content": {
          "application/json": {
            "schema": {
              "allOf": [
                {
                  "$ref": "#/components/schemas/pagination"
                },
                {
                  "required": ["data"],
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "required": [
                          "id",
                          "name",
                          "area",
                          "genre",
                          "image_url",
                          "favorite_status"
                        ],
                        "properties": {
                          "id": {
                            "type": "integer",
                            "format": "int64"
                          },
                          "name": {
                            "type": "string"
                          },
                          "area": {
                            "required": ["id", "name"],
                            "properties": {
                              "id": {
                                "type": "integer",
                                "format": "int64"
                              },
                              "name": {
                                "type": "string"
                              }
                            },
                            "type": "object"
                          },
                          "genre": {
                            "required": ["id", "name"],
                            "properties": {
                              "id": {
                                "type": "integer",
                                "format": "int64"
                              },
                              "name": {
                                "type": "string"
                              }
                            },
                            "type": "object"
                          },
                          "image_url": {
                            "type": "string",
                            "format": "uri"
                          },
                          "favorite_status": {
                            "type": "string",
                            "enum": ["unknown", "marked", "unmarked"]
                          }
                        },
                        "type": "object"
                      }
                    }
                  },
                  "type": "object"
                }
              ]
            },
            "examples": {
              "get-shops-200-empty": {
                "summary": "該当する飲食店がない場合",
                "value": {
                  "meta": {
                    "current_page": 1,
                    "from": null,
                    "last_page": 1,
                    "path": "https://api.rese.com/shops",
                    "per_page": 10,
                    "to": null,
                    "total": 0
                  },
                  "links": [
                    {
                      "url": null,
                      "label": "&laquo; Previous",
                      "active": false
                    },
                    {
                      "url": "https://api.rese.com/shops?page=1",
                      "label": "1",
                      "active": false
                    },
                    {
                      "url": null,
                      "label": "Next &raquo;",
                      "active": false
                    }
                  ],
                  "data": []
                }
              },
              "get-shops-200-first-page": {
                "summary": "1ページ目の飲食店一覧",
                "value": {
                  "meta": {
                    "current_page": 1,
                    "from": 1,
                    "last_page": 3,
                    "path": "https://api.rese.com/shops",
                    "per_page": 5,
                    "to": 5,
                    "total": 12
                  },
                  "links": [
                    {
                      "url": null,
                      "label": "&laquo; Previous",
                      "active": false
                    },
                    {
                      "url": "https://api.rese.com/shops?page=1",
                      "label": "1",
                      "active": true
                    },
                    {
                      "url": "https://api.rese.com/shops?page=2",
                      "label": "2",
                      "active": true
                    },
                    {
                      "url": "https://api.rese.com/shops?page=3",
                      "label": "3",
                      "active": true
                    },
                    {
                      "url": "https://api.rese.com/shops?page=2",
                      "label": "Next &raquo;",
                      "active": true
                    }
                  ],
                  "data": [
                    {
                      "id": 1,
                      "name": "店舗1",
                      "area": {
                        "id": 1,
                        "name": "東京都"
                      },
                      "genre": {
                        "id": 1,
                        "name": "和食"
                      },
                      "image_url": "https://api.rese.com/images/1.jpg",
                      "favorite_status": "marked"
                    },
                    {
                      "id": 2,
                      "name": "店舗2",
                      "area": {
                        "id": 2,
                        "name": "大阪府"
                      },
                      "genre": {
                        "id": 2,
                        "name": "中華"
                      },
                      "image_url": "https://api.rese.com/images/2.jpg",
                      "favorite_status": "unmarked"
                    },
                    {
                      "id": 3,
                      "name": "店舗3",
                      "area": {
                        "id": 3,
                        "name": "福岡県"
                      },
                      "genre": {
                        "id": 3,
                        "name": "イタリアン"
                      },
                      "image_url": "https://api.rese.com/images/3.jpg",
                      "favorite_status": "unknown"
                    },
                    {
                      "id": 4,
                      "name": "店舗4",
                      "area": {
                        "id": 1,
                        "name": "東京都"
                      },
                      "genre": {
                        "id": 1,
                        "name": "和食"
                      },
                      "image_url": "https://api.rese.com/images/4.jpg",
                      "favorite_status": "marked"
                    },
                    {
                      "id": 5,
                      "name": "店舗5",
                      "area": {
                        "id": 2,
                        "name": "大阪府"
                      },
                      "genre": {
                        "id": 2,
                        "name": "中華"
                      },
                      "image_url": "https://api.rese.com/images/5.jpg",
                      "favorite_status": "unmarked"
                    }
                  ]
                }
              },
              "get-shops-200-middle-page": {
                "summary": "2ページ目の飲食店一覧",
                "value": {
                  "meta": {
                    "current_page": 2,
                    "from": 6,
                    "last_page": 3,
                    "path": "https://api.rese.com/shops",
                    "per_page": 5,
                    "to": 10,
                    "total": 12
                  },
                  "links": [
                    {
                      "url": "https://api.rese.com/shops?page=1",
                      "label": "&laquo; Previous",
                      "active": true
                    },
                    {
                      "url": "https://api.rese.com/shops?page=1",
                      "label": "1",
                      "active": true
                    },
                    {
                      "url": "https://api.rese.com/shops?page=2",
                      "label": "2",
                      "active": true
                    },
                    {
                      "url": "https://api.rese.com/shops?page=3",
                      "label": "3",
                      "active": true
                    },
                    {
                      "url": "https://api.rese.com/shops?page=3",
                      "label": "Next &raquo;",
                      "active": true
                    }
                  ],
                  "data": [
                    {
                      "id": 6,
                      "name": "店舗6",
                      "area": {
                        "id": 1,
                        "name": "東京都"
                      },
                      "genre": {
                        "id": 1,
                        "name": "和食"
                      },
                      "image_url": "https://api.rese.com/images/6.jpg",
                      "favorite_status": "marked"
                    },
                    {
                      "id": 7,
                      "name": "店舗7",
                      "area": {
                        "id": 2,
                        "name": "大阪府"
                      },
                      "genre": {
                        "id": 2,
                        "name": "中華"
                      },
                      "image_url": "https://api.rese.com/images/7.jpg",
                      "favorite_status": "unmarked"
                    },
                    {
                      "id": 8,
                      "name": "店舗8",
                      "area": {
                        "id": 3,
                        "name": "福岡県"
                      },
                      "genre": {
                        "id": 3,
                        "name": "イタリアン"
                      },
                      "image_url": "https://api.rese.com/images/8.jpg",
                      "favorite_status": "unknown"
                    },
                    {
                      "id": 9,
                      "name": "店舗9",
                      "area": {
                        "id": 1,
                        "name": "東京都"
                      },
                      "genre": {
                        "id": 1,
                        "name": "和食"
                      },
                      "image_url": "https://api.rese.com/images/9.jpg",
                      "favorite_status": "marked"
                    },
                    {
                      "id": 10,
                      "name": "店舗10",
                      "area": {
                        "id": 2,
                        "name": "大阪府"
                      },
                      "genre": {
                        "id": 2,
                        "name": "中華"
                      },
                      "image_url": "https://api.rese.com/images/10.jpg",
                      "favorite_status": "unmarked"
                    }
                  ]
                }
              },
              "get-shops-200-last-page": {
                "summary": "3ページ目の飲食店一覧",
                "value": {
                  "meta": {
                    "current_page": 3,
                    "from": 11,
                    "last_page": 3,
                    "path": "https://api.rese.com/shops",
                    "per_page": 5,
                    "to": 12,
                    "total": 12
                  },
                  "links": [
                    {
                      "url": "https://api.rese.com/shops?page=2",
                      "label": "&laquo; Previous",
                      "active": true
                    },
                    {
                      "url": "https://api.rese.com/shops?page=1",
                      "label": "1",
                      "active": true
                    },
                    {
                      "url": "https://api.rese.com/shops?page=2",
                      "label": "2",
                      "active": true
                    },
                    {
                      "url": "https://api.rese.com/shops?page=3",
                      "label": "3",
                      "active": true
                    },
                    {
                      "url": null,
                      "label": "Next &raquo;",
                      "active": false
                    }
                  ],
                  "data": [
                    {
                      "id": 11,
                      "name": "店舗11",
                      "area": {
                        "id": 1,
                        "name": "東京都"
                      },
                      "genre": {
                        "id": 1,
                        "name": "和食"
                      },
                      "image_url": "https://api.rese.com/images/11.jpg",
                      "favorite_status": "marked"
                    },
                    {
                      "id": 12,
                      "name": "店舗12",
                      "area": {
                        "id": 2,
                        "name": "大阪府"
                      },
                      "genre": {
                        "id": 2,
                        "name": "中華"
                      },
                      "image_url": "https://api.rese.com/images/12.jpg",
                      "favorite_status": "unmarked"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "parameters": {
      "user-id": {
        "name": "user",
        "in": "path",
        "description": "ユーザーID",
        "required": true,
        "schema": {
          "type": "integer",
          "format": "int64",
          "example": 1
        }
      },
      "shop-id": {
        "name": "shop",
        "in": "path",
        "description": "飲食店ID",
        "required": true,
        "schema": {
          "type": "integer",
          "format": "int64",
          "example": 1
        }
      },
      "area-query": {
        "name": "area",
        "in": "query",
        "description": "エリアID",
        "required": false,
        "schema": {
          "type": "integer",
          "format": "int64"
        }
      },
      "genre-query": {
        "name": "genre",
        "in": "query",
        "description": "ジャンルID",
        "required": false,
        "schema": {
          "type": "integer",
          "format": "int64"
        }
      },
      "search-query": {
        "name": "search",
        "in": "query",
        "description": "店名検索キーワード",
        "required": false,
        "schema": {
          "type": "string"
        }
      },
      "page-query": {
        "name": "page",
        "in": "query",
        "description": "ページ番号",
        "required": false,
        "schema": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "requestBodies": {
      "post-auth-register": {
        "description": "ユーザー登録リクエスト",
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "required": ["name", "email", "password"],
              "properties": {
                "name": {
                  "description": "ユーザー名",
                  "type": "string",
                  "maxLength": 100,
                  "minLength": 1,
                  "example": "テストユーザー"
                },
                "email": {
                  "description": "メールアドレス",
                  "type": "string",
                  "format": "email",
                  "example": "test@example.com"
                },
                "password": {
                  "description": "パスワード",
                  "type": "string",
                  "maxLength": 100,
                  "minLength": 8,
                  "example": "password"
                }
              },
              "type": "object"
            }
          }
        }
      },
      "post-auth-login": {
        "description": "ログインリクエスト",
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "required": ["email", "password"],
              "properties": {
                "email": {
                  "description": "メールアドレス",
                  "type": "string",
                  "format": "email",
                  "example": "test@example.com"
                },
                "password": {
                  "description": "パスワード",
                  "type": "string",
                  "maxLength": 100,
                  "minLength": 8,
                  "example": "password"
                }
              },
              "type": "object"
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Area",
      "description": "エリアに関するAPI"
    },
    {
      "name": "Auth",
      "description": "認証に関するAPI"
    },
    {
      "name": "Customer",
      "description": "一般会員に関するAPI"
    },
    {
      "name": "Favorite",
      "description": "お気に入りに関するAPI"
    },
    {
      "name": "Genre",
      "description": "ジャンルに関するAPI"
    },
    {
      "name": "Shop",
      "description": "飲食店に関するAPI"
    }
  ]
}
